#!/usr/bin/env bash
#Diplay hour from 0 to 12 and minutes from 1 to 59.

min=1
h=0

while [ $h -le 12 ]
do
	if [ $min -eq 1 ]
	then
		echo "Hour: $h"
	fi
	echo "$min"
	((min += 1))

	if [ $min -eq 60 ]
	then
		min=1
		((h += 1))
	fi
done
